module.exports = {
    name: 'newField',
    type: 'text_general',
    indexed: true,
    stored: true,
    docValues: false,
    sortMissingFirst: false,
    sortMissingLast: false,
    multiValued: false,
    omitNorms: true,
    omitTermFreqAndPositions: false,
    omitPositions: false,
    termVectors: true,
    termPositions: false,
    termOffsets: false,
    termPayloads: false,
    required: false,
    dynamicField: false,
}
